### ISSUE TITLE
assert fails with evhtp_make_request when response callback is invoked

### ISSUE THREAD

**Issue by wolfchimneyrock** [criticalstack/libevhtp#49] opened 2017-10-30 20:11 UTC
https://github.com/criticalstack/libevhtp/blob/12ed7e8c4a6d7cfec24c5c9f1036bff9049d7a4c/evhtp.c#L2165

if I comment out the assert, everything appears to work fine

**Comment by NathanFrench** [comment] 2017-10-31 02:17
This is a duplicate of https://github.com/criticalstack/libevhtp/issues/42

We're working on it.

Cheers!

**Closed by NathanFrench** 2017-10-31 02:17 UTC
Labels: duplicate
